### ISSUE TITLE
Squiggle keeps crashing with damaged config file.

### ISSUE THREAD

**Issue by DennouNeko** [hasankhan/Squiggle#15]
I've run into an issue, when on one of system crashes the config file in AppData got damaged. I ended up with 6kB file full of zeros.
Icon in tray wasn't showing (there was only blank space) and trying to open the main window was ending up in just a blank window and app crash.
Managed to debug it a bit and got initializer of Squiggle.UI.Settings.SettingsProvider throwing 

> System.Configuration.ConfigurationErrorsException: Root element is missing.

Could provide the full stack trace, if necessary, but the important part seems to be:

> ...
>   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
>   at Squiggle.UI.Properties.Settings.get_FirstRun()
>   at Squiggle.UI.Settings.GeneralSettings.ReadFrom(Settings settings, ConfigReader reader)
>   at Squiggle.UI.Settings.SquiggleSettings.ReadFrom(Settings settings, ConfigReader reader)
>   at Squiggle.UI.Settings.SettingsProvider.Load()
> ...

**Comment by berlinchris81** [comment]
Same Problem here!

Chris

**Comment by hasankhan** [comment]
Does deleting the config file help?

**Comment by berlinchris81** [comment]
Hi in my config, i wrote a batch file which delete the damaged file and replaced it with a backed up file. Delete reset all settings. 

LG

**Comment by DennouNeko** [comment]
Yes. Deleting the config file does allow the Squiggle to launch properly. The main issue is that application doesn't seem to have any handling of malformed file and any normal user would be clueless why it's crashing - won't know that they should delete the file.
